baseURL = "https://amelie-lr.github.io/FRA3825-carnet/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Amélie Levasseur-Raymond"
theme = "cupper-hugo-theme"
enableGitInfo = true
googleAnalytics = ""

[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
posts = "/:filename/"

[imaging]
quality = 99

[params]
author = "Amélie Levasseur-Raymond"
Subtitle = ""
description = "**Amélie** Levasseur&#8209;Raymond"
homeMetaContent = ""
footer = "Les contenus de ce site sont sous [licence CC BY-NC-SA](http://creativecommons.org/licenses/by-nc-sa/4.0/) : Attribution - Pas d’utilisation commerciale - Partage dans les mêmes conditions"
dateFormat = "2 January 2006"
codePenUser = "someUser"
katex = true
hideHeaderLinks = false
search = true
showThemeSwitcher = false
defaultDarkTheme = false
moveFooterToHeader = false
logoAlt = "Amélie Levasseur-Raymond"
customCss = [ "css/custom_01.css", "css/fonts.css" ]
customJs = [ "js/custom_01.js", "js/custom_02.js" ]
instagramLink = ""


[[menu.nav]]
name = "Accueillir"
url = "/"
weight = 1

[[menu.nav]]
name = "Être"
url = "/about/"
weight = 10

[[menu.nav]]
name = "L'1nfograph3"
url = "/posts/"
weight = 20

[[menu.nav]]
name = "Étiquetter"
url = "/tags/"
weight = 30

[[menu.nav]]
name = "Ressources"
url = "/docs/"
weight = 40

[[menu.nav]]
name = "Créditer"
url = "/credits/"
weight = 50

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

  [markup.highlight]
  codeFences = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.tableOfContents]
  endLevel = 6
  startLevel = 2
